/**
 * @file uart_comm.c
 * @brief UART transport for the Jetson serial protocol
 */

#include "uart_comm.h"
#include "protocol.h"
#include "usart.h"
#include <string.h>

/* UART handle generated by CubeMX. */
extern UART_HandleTypeDef huart1;

/* RX ring buffer. */
static uint8_t rx_buffer[UART_RX_BUFFER_SIZE];
static volatile uint16_t rx_head = 0;
static volatile uint16_t rx_tail = 0;

/* DMA TX staging buffer. */
static uint8_t tx_buffer[UART_TX_BUFFER_SIZE];
static volatile uint8_t tx_busy = 0;

/* Small FIFO used when responses arrive faster than DMA can drain them. */
#define TX_QUEUE_SIZE 4
static uint8_t tx_queue[TX_QUEUE_SIZE][UART_TX_BUFFER_SIZE];
static volatile uint8_t tx_queue_len[TX_QUEUE_SIZE];
static volatile uint8_t tx_queue_head = 0;
static volatile uint8_t tx_queue_tail = 0;
static volatile uint8_t tx_queue_count = 0;

/* Single-byte interrupt reception scratch space. */
static uint8_t rx_byte;

/*
 * Parser state for frames using:
 * [HEAD][SEQ][LEN][CMD][DATA][CRC16(2)][TAIL]
 */
typedef enum {
    STATE_WAIT_HEAD,
    STATE_WAIT_SEQ,
    STATE_WAIT_LEN,
    STATE_WAIT_DATA,
    STATE_WAIT_TAIL
} UartParseState;

static UartParseState parse_state = STATE_WAIT_HEAD;
static uint8_t frame_buffer[64];
/* LEN stores the combined byte count for CMD + DATA. */
static uint8_t frame_len = 0;
static uint8_t frame_idx = 0;

static void rx_buffer_push(uint8_t data);
static int rx_buffer_pop(uint8_t* data);
static int parse_byte(uint8_t byte);

void uart_comm_init(void)
{
    rx_head = 0;
    rx_tail = 0;
    tx_busy = 0;
    parse_state = STATE_WAIT_HEAD;
    frame_idx = 0;
    frame_len = 0;

    /* Reset the pending TX queue. */
    tx_queue_head = 0;
    tx_queue_tail = 0;
    tx_queue_count = 0;

    /* Receive one byte at a time and rebuild frames in software. */
    HAL_UART_Receive_IT(&huart1, &rx_byte, 1);
}

/* Push one byte into the RX ring buffer from ISR context. */
static void rx_buffer_push(uint8_t data)
{
    uint16_t next = (rx_head + 1) % UART_RX_BUFFER_SIZE;
    if (next != rx_tail)
    {
        rx_buffer[rx_head] = data;
        rx_head = next;
    }

    /* Drop the newest byte if the ring buffer is full. */
}

/* Pop one byte from the RX ring buffer in main-loop context. */
static int rx_buffer_pop(uint8_t* data)
{
    if (rx_head == rx_tail)
    {
        return 0;
    }

    /* Protect head/tail updates against concurrent ISR access. */
    __disable_irq();
    *data = rx_buffer[rx_tail];
    rx_tail = (rx_tail + 1) % UART_RX_BUFFER_SIZE;
    __enable_irq();

    return 1;
}

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART1)
    {
        rx_buffer_push(rx_byte);
        HAL_UART_Receive_IT(&huart1, &rx_byte, 1);
    }
}

/* Continue draining queued TX frames when a DMA send completes. */
void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART1)
    {
        /* Send the next queued frame if one is waiting. */
        if (tx_queue_count > 0)
        {
            uint8_t len = tx_queue_len[tx_queue_tail];
            if (len > 0 && len <= UART_TX_BUFFER_SIZE)
            {
                memcpy(tx_buffer, tx_queue[tx_queue_tail], len);
                tx_queue_tail = (tx_queue_tail + 1) % TX_QUEUE_SIZE;
                tx_queue_count--;

                /* Keep tx_busy asserted while the next DMA transfer is active. */
                if (HAL_UART_Transmit_DMA(&huart1, tx_buffer, len) != HAL_OK)
                {
                    tx_busy = 0;
                }
                return;
            }
        }

        /* Queue is empty, so TX is now idle. */
        tx_busy = 0;
    }
}

/* Return 1 once a complete frame has been assembled in frame_buffer. */
static int parse_byte(uint8_t byte)
{
    switch (parse_state)
    {
        case STATE_WAIT_HEAD:
            if (byte == FRAME_HEAD)
            {
                frame_idx = 0;
                frame_buffer[frame_idx++] = byte;
                parse_state = STATE_WAIT_SEQ;
            }
            break;

        case STATE_WAIT_SEQ:
            /* Every 8-bit sequence number is valid, so just store it. */
            if (frame_idx < sizeof(frame_buffer))
            {
                frame_buffer[frame_idx++] = byte;
                parse_state = STATE_WAIT_LEN;
            }
            else
            {
                parse_state = STATE_WAIT_HEAD;
                frame_idx = 0;
            }
            break;

        case STATE_WAIT_LEN:
            /* LEN counts CMD plus payload bytes. */
            frame_len = byte;
            if (frame_idx < sizeof(frame_buffer) &&
                frame_len > 0 &&
                frame_len <= (FRAME_MAX_DATA_LEN + 1))
            {
                frame_buffer[frame_idx++] = byte;
                parse_state = STATE_WAIT_DATA;
            }
            else
            {
                /* Invalid length, drop the partial frame. */
                parse_state = STATE_WAIT_HEAD;
                frame_idx = 0;
            }
            break;

        case STATE_WAIT_DATA:
            /*
             * Read CMD + DATA + CRC16.
             * Bytes already stored: HEAD + SEQ + LEN = 3.
             * Total without TAIL = 3 + frame_len + 2 = frame_len + 5.
             */
            if (frame_idx < sizeof(frame_buffer))
            {
                frame_buffer[frame_idx++] = byte;
                if (frame_idx >= (uint8_t)(frame_len + 5))
                {
                    parse_state = STATE_WAIT_TAIL;
                }
            }
            else
            {
                /* Buffer overflow, reset the parser. */
                parse_state = STATE_WAIT_HEAD;
                frame_idx = 0;
            }
            break;

        case STATE_WAIT_TAIL:
            /* Consume the trailing FRAME_TAIL marker. */
            if (frame_idx < sizeof(frame_buffer))
            {
                frame_buffer[frame_idx++] = byte;
            }
            parse_state = STATE_WAIT_HEAD;
            if (byte == FRAME_TAIL)
            {
                return 1;
            }

            /* Tail mismatch, discard the frame. */
            frame_idx = 0;
            break;

        default:
            /* Unknown state should never happen, but recover safely. */
            parse_state = STATE_WAIT_HEAD;
            frame_idx = 0;
            break;
    }

    return 0;
}

void uart_comm_process(CommandCallback callback)
{
    uint8_t byte;
    Command cmd;

    while (rx_buffer_pop(&byte))
    {
        if (parse_byte(byte))
        {
            if (cmd_parse(frame_buffer, frame_idx, &cmd) == PARSE_OK)
            {
                if (callback)
                {
                    callback(&cmd);
                }
            }
        }
    }
}

/*
 * Encode the response into a temporary buffer first so we never mutate the
 * shared DMA staging buffer while another transfer may still be using it.
 */
void uart_comm_send_response(const Response* rsp)
{
    uint8_t tmp_buf[UART_TX_BUFFER_SIZE];
    size_t len = cmd_encode(rsp, tmp_buf);
    if (len == 0 || len > UART_TX_BUFFER_SIZE)
    {
        return;
    }

    /*
     * The tx_busy check, buffer copy, and DMA start need to appear atomic
     * relative to HAL_UART_TxCpltCallback.
     */
    __disable_irq();

    if (!tx_busy)
    {
        memcpy(tx_buffer, tmp_buf, len);
        tx_busy = 1;
        __enable_irq();

        if (HAL_UART_Transmit_DMA(&huart1, tx_buffer, (uint16_t)len) != HAL_OK)
        {
            __disable_irq();
            tx_busy = 0;
            __enable_irq();
        }
        return;
    }

    /* TX is busy, so push into the software queue if space remains. */
    if (tx_queue_count < TX_QUEUE_SIZE)
    {
        memcpy(tx_queue[tx_queue_head], tmp_buf, len);
        tx_queue_len[tx_queue_head] = (uint8_t)len;
        tx_queue_head = (tx_queue_head + 1) % TX_QUEUE_SIZE;
        tx_queue_count++;
    }
    /* Drop the response if the queue is already full. */

    __enable_irq();
}
